
sudo: required

language: node_js

node_js:
  - '6'

before_install:
  - sudo apt-get update -y

before_script:
  - chmod +x sh/*

addons:
  apt:
    packages:
      - make
      - cmake
      - gcc
      - g++
      - p7zip
